BINARY_FOLDER="./bin"
TIMESTAMP=$(shell date +%s)

build:
	rm -f ${BINARY_FOLDER}/*
	GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'main.buildDateUnix=${TIMESTAMP}'" -o ${BINARY_FOLDER}/mthe_darwin_arm64 -v ./...
	GOOS=linux  GOARCH=amd64 go build -ldflags="-X 'main.buildDateUnix=${TIMESTAMP}'" -o ${BINARY_FOLDER}/mthe_linux_amd64 -v ./...
	GOOS=linux  GOARCH=arm64 go build -ldflags="-X 'main.buildDateUnix=${TIMESTAMP}'" -o ${BINARY_FOLDER}/mthe_linux_arm64 -v ./...
